services:
  server:
    build:
      context: .
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    develop:
      watch:
        - path: pom.xml
          action: rebuild
        - path: src
          target: /app/src
          action: sync

  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
